// How each section of the PDF (source/Sepire_Statement_v1.1.pdf, 13 pages, US Letter
// 612 × 792 pt) maps to the interactive statement. Rectangles are PDF points [x0, y0, x1, y1],
// measured from the PDF's text layout (scripts/render-pdf.py --spans).

export type Mapping = {
  id: string;
  page: number;
  rect: [number, number, number, number];
  title: string;
  route: string;
  target: string;
  before: string;
  after: string;
  why: string;
};

export const PDF_PAGES = 13;
export const PAGE_SIZE = { w: 612, h: 792 };
/** Pages of the statement's own print edition (the PDF's page 13 design reference is not printed). */
export const PRINT_SHEETS = 12;

export const PAGE_TITLES: Record<number, string> = {
  1: 'Summary & account at a glance',
  2: 'Activity by source and investment',
  3: 'Holdings & asset allocation',
  4: 'Lifetime income estimate',
  5: 'Lifetime income illustrations',
  6: 'Loans, beneficiaries & expenses',
  7: 'Right to direct investments',
  8: 'Notices & disclosures',
  9: 'Appendix: history & projection',
  10: 'Appendix: limits & vesting',
  11: 'Appendix: contributions & performance',
  12: 'Appendix: repayments, Roth & profile',
  13: 'Appendix: design reference',
};

export const MAPPINGS: Mapping[] = [
  {
    id: 'p1-addressee',
    page: 1,
    rect: [36, 80, 214, 218],
    title: 'Address block → personal greeting',
    route: '/overview',
    target: '[data-focus-id="section:hero"]',
    before: 'A mailing-address block laid out for an envelope window.',
    after: 'A personal greeting that leads with Sidney’s ending balance and a plain-language summary of the period.',
    why: 'Digital delivery doesn’t need an envelope window. The first thing the participant reads answers their first question: how am I doing?',
  },
  {
    id: 'p1-branding',
    page: 1,
    rect: [36, 34, 296, 78],
    title: 'Logos & co-branding',
    route: '/overview',
    target: '.brand-lockup',
    before: 'Two grey boxes reserved for “YOUR LOGO” and “CO-BRANDED”.',
    after: 'Sepire and the plan sponsor share a live header with the plan name, period, language switch and print button.',
    why: 'Co-branding becomes configuration rather than redesign: each sponsor’s identity drops into the same template.',
  },
  {
    id: 'p1-plan',
    page: 1,
    rect: [316, 32, 576, 138],
    title: 'Plan header & service contacts',
    route: '/plan-profile/contacts',
    target: '.pp-service',
    before: 'Plan name, number and period, plus three lines of contact text to read and retype.',
    after: 'Tap-to-call, tap-to-email and a direct link to the participant website, grouped with the plan’s service team.',
    why: 'Contact details become actions. Fewer steps from question to answer means fewer abandoned inquiries.',
  },
  {
    id: 'p1-advisors',
    page: 1,
    rect: [316, 150, 576, 224],
    title: 'Your financial professionals',
    route: '/plan-profile/contacts',
    target: '[data-focus-id="section:financial-professionals"]',
    before: 'Two names, each with a phone number and an email address.',
    after: 'Contact cards with one-tap calling and email for each financial professional.',
    why: 'Advisers the sponsor has already arranged become easy to reach, supporting the advice relationship.',
  },
  {
    id: 'p1-access',
    page: 1,
    rect: [316, 230, 576, 322],
    title: 'Access your account (QR)',
    route: '/plan-profile/contacts',
    target: '[data-focus-id="section:account-access"]',
    before: 'A QR code and a login address to type in.',
    after: 'A working QR code generated in the statement plus an “Open participant login” button; the same code prints on paper.',
    why: 'This is the shortest path from reading to acting, for example changing a deferral rate right after seeing the limit gauges.',
  },
  {
    id: 'p1-message',
    page: 1,
    rect: [36, 338, 576, 388],
    title: 'Plan-sponsor message',
    route: '/overview',
    target: '[data-focus-id="section:plan-message"]',
    before: 'A text block for the sponsor’s message, fixed when the statement is produced.',
    after: 'A configurable message slot managed in CompliChain®, updated every cycle without touching the statement design.',
    why: 'Timely news (enrollment windows, fund changes, match updates) reaches participants without a template change or a reprint.',
  },
  {
    id: 'p1-balance',
    page: 1,
    rect: [36, 400, 296, 492],
    title: 'Ending balance',
    route: '/overview',
    target: '[data-focus-id="section:balance"]',
    before: 'The ending balance in large type.',
    after: 'The ending balance with the net change (marked as calculated), the rate of return and a link back to page 1.',
    why: 'The number participants care about most comes with the context needed to read it correctly.',
  },
  {
    id: 'p1-glance',
    page: 1,
    rect: [36, 494, 296, 676],
    title: 'Account at a glance',
    route: '/overview',
    target: '[data-focus-id="section:balance-bridge"]',
    before: 'A seven-row table from beginning balance to ending balance.',
    after: 'An interactive balance bridge: each activity is a step to select, explain with Sepi or drill into. The exact table is one click away.',
    why: 'It answers “why did my balance change?”, one of the most common service questions, without a phone call.',
  },
  {
    id: 'p1-return',
    page: 1,
    rect: [36, 684, 296, 742],
    title: 'Account rate of return',
    route: '/overview',
    target: '[data-focus-id="section:rate-of-return"]',
    before: 'Two percentages in a shaded box.',
    after: 'Quarter and year-to-date returns with an inline definition and “Explain with Sepi”.',
    why: 'A one-tap explanation prevents a common misreading: the rate of return is not the same as the change in balance.',
  },
  {
    id: 'p1-allocation',
    page: 1,
    rect: [316, 400, 576, 600],
    title: 'Investment allocation summary',
    route: '/overview',
    target: '[data-focus-id="section:allocation"]',
    before: 'Five category bars with percentages.',
    after: 'An interactive donut: select a category to see its funds and jump to full holdings.',
    why: 'Understanding diversification at a glance is the first step toward engaged, informed investment choices.',
  },
  {
    id: 'p2-sources',
    page: 2,
    rect: [36, 64, 576, 250],
    title: 'Account summary by contribution source',
    route: '/activity/sources',
    target: '[data-focus-id="section:sources"]',
    before: 'A dense eight-column table of activity by money source.',
    after: 'Each source summarized visually above the exact statement table. Blank cells stay blank instead of becoming $0.',
    why: 'Participants see whose money is whose (theirs, the employer’s, safe harbor) without decoding columns.',
  },
  {
    id: 'p2-investments',
    page: 2,
    rect: [36, 252, 576, 500],
    title: 'Account summary by investment',
    route: '/activity/investments',
    target: '[data-focus-id="section:investments"]',
    before: 'The same eight-column table, this time by fund.',
    after: 'Activity by fund with the exact table preserved and every row open to Tag, Ask or Explain.',
    why: 'Row-level actions turn a reference table into a starting point for questions.',
  },
  {
    id: 'p3-holdings',
    page: 3,
    rect: [36, 76, 576, 366],
    title: 'Holdings with share details',
    route: '/investments/holdings',
    target: '[data-focus-id="section:holdings"]',
    before: 'Eight funds with ticker, shares, price, ending balance and % of total.',
    after: 'A composition bar and fund rows showing shares × price, with loans shown separately so both totals make sense.',
    why: 'Participants understand what they own, and why the account total including loans differs from the investment total.',
  },
  {
    id: 'p3-allocation',
    page: 3,
    rect: [36, 380, 576, 762],
    title: 'Asset allocation vs. investment election',
    route: '/investments/allocation',
    target: 'section.inv-achart',
    before: 'Allocation, election and deviation columns grouped by category.',
    after: 'A deviation chart that shows at a glance where each fund sits against the participant’s election.',
    why: 'Drift is invisible in a table and obvious in a chart, which prompts a timely review without the statement giving advice.',
  },
  {
    id: 'p4-lifetime',
    page: 4,
    rect: [36, 64, 576, 420],
    title: 'Lifetime income estimate',
    route: '/retirement-income/lifetime-estimate',
    target: '[data-focus-id="section:lifetime"]',
    before: 'Three large numbers and two paragraphs defining annuity forms.',
    after: 'The federally required illustration as a clear infographic (single life vs. joint & 100% survivor) with the definitions kept verbatim.',
    why: 'It meets the lifetime-income disclosure requirement while making “monthly income for life” tangible.',
  },
  {
    id: 'p5-assumed',
    page: 5,
    rect: [36, 110, 576, 495],
    title: 'What we assumed',
    route: '/retirement-income/assumptions',
    target: '[data-focus-id="section:assumed"]',
    before: 'Seven dense paragraphs of regulatory assumptions.',
    after: 'Each assumption as a numbered card with a plain-language summary; the exact regulatory wording is kept verbatim.',
    why: 'Required disclosures stay intact for compliance, and a scannable layout means they actually get read.',
  },
  {
    id: 'p5-not-tell',
    page: 5,
    rect: [36, 497, 576, 672],
    title: 'What these estimates don’t tell you',
    route: '/retirement-income/assumptions',
    target: '[data-focus-id="section:not-tell"]',
    before: 'A shaded box of caveats.',
    after: 'The caveats stay prominent, right beside the estimate they qualify.',
    why: 'Clear limits on an illustration protect participants from over-relying on it, and protect the plan.',
  },
  {
    id: 'p5-differs',
    page: 5,
    rect: [36, 676, 576, 768],
    title: 'Illustration vs. readiness projection',
    route: '/retirement-income',
    target: '[data-focus-id="section:how-differs"]',
    before: 'A paragraph explaining why two income estimates differ.',
    after: 'Both estimates side by side, color-coded (required illustration vs. planning estimate) and explained point by point.',
    why: 'It prevents the most common misreading of retirement-income figures.',
  },
  {
    id: 'p6-loans',
    page: 6,
    rect: [36, 64, 576, 216],
    title: 'Loan summary',
    route: '/loans-beneficiaries/loans',
    target: '[data-focus-id="section:payoff-timeline"]',
    before: 'A nine-column loan table.',
    after: 'Loan cards with a payoff timeline, principal vs. interest paid this period, and the exact table as evidence.',
    why: 'Participants see when each loan ends and what it costs, which supports responsible borrowing.',
  },
  {
    id: 'p6-beneficiaries',
    page: 6,
    rect: [36, 220, 576, 442],
    title: 'Beneficiaries',
    route: '/loans-beneficiaries/beneficiaries',
    target: '.lb-ben-grid',
    before: 'Names, relationships, partial tax IDs, dates of birth and addresses in full view.',
    after: 'Allocation rings for primary and contingent beneficiaries, sensitive fields masked until revealed, plus when-to-review guidance.',
    why: 'Privacy by default, and a nudge to keep designations current after life events.',
  },
  {
    id: 'p6-expenses',
    page: 6,
    rect: [36, 446, 576, 732],
    title: 'Plan expenses',
    route: '/activity/fees',
    target: '[data-focus-id="section:fees"]',
    before: 'Administrative and individual expenses in two text columns.',
    after: 'A visual fee breakdown with descriptions, subtotals and the total deducted; each fee is open to questions.',
    why: 'Fee transparency builds trust and meets disclosure expectations.',
  },
  {
    id: 'p7-direction',
    page: 7,
    rect: [36, 64, 576, 500],
    title: 'Your right to direct investments',
    route: '/investments/direction',
    target: '[data-focus-id="section:direction"]',
    before: 'A page of rules with bracketed plan-specific terms.',
    after: 'Explorable rule cards (frequent trading, minimums, blackout periods, default investment) with the full text as printed.',
    why: 'Participants understand their rights and limits, which supports ERISA 404(c) communication.',
  },
  {
    id: 'p8-notices',
    page: 8,
    rect: [36, 64, 576, 380],
    title: 'Important notices & disclosures',
    route: '/plan-profile/disclosures',
    target: '[data-focus-id="disclosure:diversification"]',
    before: 'A page of small-print paragraphs.',
    after: 'Each notice with a plain-language summary; expand any one to read the exact text.',
    why: 'Required notices stay complete and verbatim, and become findable and readable.',
  },
  {
    id: 'p9-history',
    page: 9,
    rect: [36, 134, 576, 272],
    title: 'Balance history',
    route: '/overview',
    target: '[data-focus-id="section:balance-history"]',
    before: 'A static six-year bar chart.',
    after: 'The same bars, drawn from the source chart, with the statement year emphasized.',
    why: 'Long-term progress motivates saving more than a single period’s change.',
  },
  {
    id: 'p9-projection',
    page: 9,
    rect: [36, 274, 576, 640],
    title: 'Projected retirement income',
    route: '/retirement-income/readiness',
    target: '[data-focus-id="section:readiness"]',
    before: 'Projected income, progress toward a goal and a one-line suggestion to save $30 more.',
    after: 'A readiness projection linked to an interactive scenario modeler.',
    why: 'A passive suggestion becomes an active what-if, and that is what moves savings rates.',
  },
  {
    id: 'p10-limits',
    page: 10,
    rect: [36, 95, 576, 276],
    title: 'Contribution limit monitoring',
    route: '/activity/limits',
    target: '[data-focus-id="section:limits"]',
    before: 'Two figures with thin progress bars and a paragraph of IRS rules.',
    after: 'Gauges for the elective-deferral and catch-up limits, with the remaining room called out.',
    why: 'Visible headroom prompts participants to make full use of their limits.',
  },
  {
    id: 'p10-vesting',
    page: 10,
    rect: [36, 287, 576, 462],
    title: 'Vesting summary',
    route: '/activity/vesting',
    target: '[data-focus-id="section:vesting"]',
    before: 'A three-row vesting table.',
    after: 'Vesting by source with a clear headline: 100% vested.',
    why: 'Ownership is clear at a glance, which matters most before a job change.',
  },
  {
    id: 'p11-contributions',
    page: 11,
    rect: [36, 95, 576, 244],
    title: 'Contribution activity with vesting',
    route: '/activity/vesting',
    target: '[data-focus-id="section:contribution-activity"]',
    before: 'A five-column table of contributions and vesting by source.',
    after: 'One progressive view: this period and year-to-date first, vesting detail on demand.',
    why: 'Participants get the summary they need without losing the detail auditors expect.',
  },
  {
    id: 'p11-performance',
    page: 11,
    rect: [36, 254, 576, 616],
    title: 'Investment performance summary',
    route: '/investments/performance',
    target: '.inv-snap',
    before: 'A ten-column performance table.',
    after: 'A performance view with period emphasis and a neutral heatmap, beside the exact table.',
    why: 'Participants compare funds meaningfully without being overwhelmed, and the past-performance caveat stays visible.',
  },
  {
    id: 'p12-repayments',
    page: 12,
    rect: [36, 95, 576, 292],
    title: 'Distributions eligible for repayment',
    route: '/activity/repayments',
    target: '[data-focus-id="section:repayments"]',
    before: 'A table with a small “61 days remaining” note.',
    after: 'A deadline timeline that counts down each repayment window.',
    why: 'Time-sensitive opportunities are hard to miss, protecting the participant’s tax position.',
  },
  {
    id: 'p12-roth',
    page: 12,
    rect: [36, 300, 350, 500],
    title: 'Amounts subject to Roth recapture tax',
    route: '/activity/roth',
    target: '[data-focus-id="section:roth"]',
    before: 'A six-column table of Roth rollover windows.',
    after: 'Five-year windows visualized, with the amount currently subject to recapture tax highlighted.',
    why: 'It helps prevent costly surprises from early distributions.',
  },
  {
    id: 'p12-profile',
    page: 12,
    rect: [366, 300, 576, 640],
    title: 'Profile information',
    route: '/plan-profile/profile',
    target: '[data-focus-id="section:profile"]',
    before: 'Email, dates, employee number and settings printed in full.',
    after: 'A protected profile: sensitive fields stay masked until the participant reveals them.',
    why: 'Personal data isn’t exposed on shared screens or printers by default.',
  },
  {
    id: 'p13-options',
    page: 13,
    rect: [36, 95, 576, 742],
    title: 'Design reference: three table options',
    route: '/activity/vesting',
    target: '[data-focus-id="section:contribution-activity"]',
    before: 'Three alternative tables of the same data on one page, “choose one for production”.',
    after: 'No compromise: one progressive-disclosure view replaces all three, with the summary first and full detail on demand.',
    why: 'Participants choose the depth they need, and the plan no longer trades simplicity against completeness.',
  },
];

export const mappingsForPage = (page: number) => MAPPINGS.filter((m) => m.page === page);
